#!/usr/bin/env ruby
require 'json'
require 'yaml'
require 'fileutils'

files = ARGV.length() == 0 ? Dir["source/swagger/*"] : ARGV

files.each do |file_name|
  if !File.directory? file_name
    file_name = file_name.gsub('source/swagger/','')
    file_name = "source/swagger/#{file_name}"
  
    if !File.file? file_name
      puts "File doen't exist: #{file_name}"
      break
    end
  
    if !file_name[/\.yaml/] && !file_name[/\.yml/]
      puts "Must be a swagger file: #{file_name}"
  
      break
    end

    input =  JSON.pretty_generate(YAML.load_file(file_name))
    parsedInput = JSON.parse(input)
    unless parsedInput
      puts "Failed to parse file: #{file_name}"
      break
    else
      newFileName = "-#{parsedInput['info']['version']}.json"
      File.open("#{file_name.gsub(/\.yaml|\.yml/, newFileName).gsub(/source\/swagger/,'source/generated-jsons')}", 'w') do |out|
        out.write input
      end
    end
  end
end