#!/usr/bin/env ruby
require 'json'
require 'yaml'
require 'fileutils'

NEW_API_DIRECTORY = 'source/swagger/generated-jsons/swagger'

files = ARGV.length() == 0 ? Dir["source/swagger/*"] : ARGV
FileUtils.mkdir_p NEW_API_DIRECTORY

files.each do |file_name|
  if !File.directory? file_name
    file_name = file_name.gsub('source/swagger/','')
    file_name = "source/swagger/#{file_name}"
  
    if !File.file? file_name
      puts "File doen't exist: #{file_name}"
      break
    end
  
    if file_name[/\.yaml/]
      input =  JSON.pretty_generate(YAML.load_file(file_name))
      parsedInput = JSON.parse(input)
      unless parsedInput
        puts "Failed to parse file: #{file_name}"
        break
      else
        newFileName = "#{parsedInput['info']['version']}.json"
        newApiDirectory =  "#{NEW_API_DIRECTORY}/#{file_name
          .gsub(/^(source\/swagger\/swagger_)(.*)(.yaml)/,"\\2")
          .gsub('_apis','')}"
          .gsub('_','-')
        newApiDirectory = "#{newApiDirectory}/doc"
        FileUtils.mkdir_p newApiDirectory

        # File.open("#{file_name.gsub(/\.yaml|\.yml/, newFileName).gsub('source/swagger', newApiDirectory)}", 'w') do |out|
        #   out.write input
        # end

        File.open("#{newApiDirectory}/#{newFileName}", 'w') do |out|
          out.write input
        end
      end
    end
  end
end
