name: Build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    name: Build SlateDocs
    runs-on: ubuntu-latest
    env:
      ruby-version: 2.5
      enable-openapi-integration: ${{ github.repository ==  'Sensedia/areadesenvolvedor' && github.ref_name != 'master'}}
      is-deploy-branch: ${{ startsWith(github.ref_name, 'GT-PR') && github.repository ==  'Sensedia/areadesenvolvedor'  }}

    steps:
      - run: sudo apt-get purge ruby 
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby-version }}
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: gems-${{ runner.os }}-${{ env.ruby-version }}-${{ hashFiles('**/Gemfile.lock') }}
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: npm install -g widdershins
      - run: npm install -g @apidevtools/swagger-cli

      - uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-${{ hashFiles('**/source') }}

      - name: Compile Swagger Files
        run: |
          cd documentation
          bash ./compile-swagger-files.sh

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.7.0
        with:
          file_glob: 'documentation/source/swagger/*_apis.yaml'

      ####################################
      # Open Api Github Repo Integration #
      ####################################
      
      # 1. Clean generated-sources folder
      # 2. Parse YAML to JSON
      # 3. Store GIT variables for next steps
      - name: Parse YAML to JSON and store GIT variables for next steps
        if: ${{ env.enable-openapi-integration }}
        id: repoIntegration
        run: |
          rm -rf ./open-api-repository-integration/generated-sources
          cd open-api-repository-integration
          ruby yaml2json.rb
          cd ..
          echo "::set-output name=git_user_name::$(git --no-pager log --format=format:'%an' -n 1)"
          echo "::set-output name=git_user_email::$(git --no-pager log --format=format:'%ae' -n 1)"
          echo "::set-output name=git_commit_message::$(git --no-pager log --format=format:'%B' -n 1)"

      # 4. Compress build folder in tar.gz format to deploy.
      - name: Compress open-api-repository-integration folder
        if: success() && env.is-deploy-branch == 'true'
        run: |
          tar -cvzf build.tar.gz open-api-repository-integration

      # 5. Upload build.tar.gz built in previous step to Github repository artifacts.
      - uses: actions/upload-artifact@v2
        if: success() && env.is-deploy-branch == 'true'
        with:
          name: build_folder_artifact
          path: build.tar.gz
          retention-days: 1

      # 6. Invoke Deploy Workflow passing the workflow parameters.
      - name: Invoke deploy workflow
        if: success() && env.is-deploy-branch == 'true'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy
          token: ${{ secrets.AREADEV_INTEGRATION }}
          inputs: |
              { 
                  "build_id": "${{ github.run_id }}" ,
                  "git_user_email": "${{ steps.repoIntegration.outputs.git_user_email }}" ,
                  "git_user_name": "${{ steps.repoIntegration.outputs.git_user_name }}",
                  "git_commit_message": "${{ steps.repoIntegration.outputs.git_commit_message }}"
              }