name: Deploy
on:
  workflow_dispatch:
    inputs:
      build_id:
        description: 'ID of build to deploy'     
        required: true
      git_user_email:
        description: 'Git user e-mail'
        required: true
      git_user_name:
        description: 'Git user name'
        required: true
      git_commit_message:
        description: 'Git commit message'
        required: true
jobs:
  deploy:
    name: Deploy Github pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    env:
      ruby-version: 2.5
    steps:
      - uses: actions/checkout@v2

      #############################################
      # Deploy artifact built in 'Build' Workflow #
      #############################################
      
      # 1. Download build.tar.gz from Github repository artifacts
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.AREADEV_INTEGRATION}}
          workflow: build.yml
          branch: ${{ github.ref_name }}
          run_id: ${{ github.event.inputs.build_id }}
          name: build_folder_artifact
          path: .

      # 2. Extract build.tar.gz and copy files to build
      - name: Extract build.tar.gz and copy files to build
        run: | 
          tar -zxvf build.tar.gz
          ls -la
          ls -la open-api-repository-integration
          pwd
 
      - name: "'Sensedia/openapi' Integration"
        if: ${{ env.enable-openapi-integration }}
        run: |
          cd open-api-repository-integration
          bash git-repository-integration.sh "${{ github.event.inputs.git_user_email }}"\
           "${{ github.event.inputs.git_user_name }}"\
           "${{ secrets.AREADEV_INTEGRATION }}"\
           "${{ github.ref_name }}"\
           "openapi"\
           "${{ github.event.inputs.git_commit_message }}"
      - name: "'Sensedia/draft-openapi' Integration"
        if: ${{ env.enable-openapi-integration }}
        run: |
          cd open-api-repository-integration
          bash git-repository-integration.sh "${{ github.event.inputs.git_user_email }}"\
           "${{ github.event.inputs.git_user_name }}"\
           "${{ secrets.AREADEV_INTEGRATION }}"\
           "${{ github.ref_name }}"\
           "draft-openapi"\
           "${{ github.event.inputs.git_commit_message }}"

      #3. Deploy files in documentation/build
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./documentation/build
      