name: Deploy
on:
  workflow_dispatch:
    inputs:
      build_id:
        description: 'ID of build to deploy'     
        required: true
  

jobs:
  deploy:
    name: Deploy Github pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: documentation
    env:
      ruby-version: 2.5

    steps:
      - uses: actions/checkout@v2
      - run: ls -la documentation/build
      - name: Download artifact
      - uses: dawidd6/action-download-artifact@v2
        with:
          # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
          # Required, if artifact is from a different repo
          # Required, if repo is private a Personal Access Token with `repo` scope is needed
          github_token: ${{secrets.AREADEV_INTEGRATION}}
          # Required, workflow file name or ID
          workflow: build.yml
          # Optional, will use the branch
          branch: 'ORB-486'
          # Optional, will use specified workflow run
          run_id: ${{ github.event.inputs.build_id }}
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them in respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          name: testing_artifact
          # Optional, directory where to extract artifact. Defaults to the artifact name (see `name` input)
          path: ./documentation/build
      - name: bash
      - run: ls -la documentation/build

      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: ${{ env.ruby-version }}
      # - run: |
        # ARTIFACT_URL=echo $(curl -4 -H "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/Sensedia/areadesenvolvedor/actions/runs/${{ github.event.inputs.build_id }}/artifacts" | jq '.artifacts[0].archive_download_url')
        # echo $ARTIFACT_URL 
        # REDIRECTED_URL=echo $(curl -i -u senseRmginner:${{ secrets.AREADEV_INTEGRATION }} -H "Accept: application/vnd.github.v3+json" $ARTIFACT_URL | sed -En 's/(location|Location): (.*)/\2/p')
        # echo $REDIRECTED_URL
        # ls -la 

      # - uses: actions/setup-node@v1
      #   with:
      #     node-version: "12"

      # - run: npm install -g widdershins
      # - run: npm install -g @apidevtools/swagger-cli
      # - name: Download a single artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: deploy-files
      # - run: |
      #     tar -zxvf build.tar.gz
      #     mv build ./documentation
      ###
      #ATENÇÃO: não é parar ligar a automação da Fase 1 sem a autorização do comitê de Open Banking
      # Open Banking Fase 1
      #- run: swagger-cli bundle source/swagger/parts/_open_banking_fase1_apis_part.yml --outfile source/swagger/swagger_open_banking_fase1_apis.yml --type=yaml
      ###

      # Open Banking Fase 2
      # - run: swagger-cli bundle source/swagger/parts/_consents_apis_part.yml --outfile source/swagger/swagger_consents_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_resources_apis_part.yml --outfile source/swagger/swagger_resources_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_customers_apis_part.yml --outfile source/swagger/swagger_customers_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_accounts_apis_part.yml --outfile source/swagger/swagger_accounts_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_credit_cards_apis_part.yml --outfile source/swagger/swagger_credit_cards_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_loans_apis_part.yml --outfile source/swagger/swagger_loans_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_financings_apis_part.yml --outfile source/swagger/swagger_financings_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_unarranged_accounts_overdraft_apis_part.yml --outfile source/swagger/swagger_unarranged_accounts_overdraft_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_invoice_financings_apis_part.yml --outfile source/swagger/swagger_invoice_financings_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_open_banking_fase2_apis_part.yml --outfile source/swagger/swagger_open_banking_fase2_apis.yml --type=yaml

      # Open Banking Fase 3
      # - run: swagger-cli bundle source/swagger/parts/_payments_apis_part.yml --outfile source/swagger/swagger_payments_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_open_banking_fase3_apis_part.yml --outfile source/swagger/swagger_open_banking_fase3_apis.yml --type=yaml

      # Open Banking Fase 4
      # - run: swagger-cli bundle source/swagger/parts/_capitalization_bonds_apis_part.yml --outfile source/swagger/swagger_capitalization_bonds_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_investments_apis_part.yml --outfile source/swagger/swagger_investments_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_insurances_apis_part.yml --outfile source/swagger/swagger_insurances_apis.yaml --type=yaml
      # - run: swagger-cli bundle source/swagger/parts/_open_banking_fase4_apis_part.yml --outfile source/swagger/swagger_open_banking_fase4_apis.yml --type=yaml

      # - run: ./build-dictionary.sh
      # - run: sed -i '1s/^\(\xef\xbb\xbf\)\?/\xef\xbb\xbf/' source/swagger/swagger_*

      # Open Banking Fase 1
      # - run: swagger-cli validate source/swagger/swagger_open_banking_fase1_apis.yml

      # Open Banking Fase 2
      # - run: swagger-cli validate source/swagger/swagger_consents_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_resources_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_customers_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_credit_cards_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_accounts_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_loans_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_financings_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_unarranged_accounts_overdraft_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_invoice_financings_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_open_banking_fase2_apis.yml

      # Open Banking Fase 3
      # - run: swagger-cli validate source/swagger/swagger_payments_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_open_banking_fase3_apis.yml

      # Open Banking Fase 4
      # - run: swagger-cli validate source/swagger/swagger_capitalization_bonds_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_investments_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_insurances_apis.yaml
      # - run: swagger-cli validate source/swagger/swagger_open_banking_fase4_apis.yml

      ###
      #ATENÇÃO: não é parar ligar a automação da Fase 1 sem a autorização do comitê de Open Banking
      #- run: widdershins source/swagger/swagger_open_banking_fase1_apis.yml -o source/includes/partials_open_banking/_open_banking_fase1_apis.md.erb --user_templates source/templates/openapi3/ --language_tabs "javascript:JavaScript:request" "python:Python:request" "java:Java::request" --omitHeader --summary --httpsnippet
      ###

      # - run: widdershins source/swagger/swagger_open_banking_fase2_apis.yml -o source/includes/partials_open_banking/_open_banking_fase2_apis.md.erb --user_templates source/templates/openapi3/ --language_tabs "javascript:JavaScript:request" "python:Python:request" "java:Java::request" --omitHeader --summary --httpsnippet
      # - run: widdershins source/swagger/swagger_open_banking_fase3_apis.yml -o source/includes/partials_open_banking/_open_banking_fase3_apis.md.erb --user_templates source/templates/openapi3/ --language_tabs "javascript:JavaScript:request" "python:Python:request" "java:Java::request" --omitHeader --summary --httpsnippet
      # - run: widdershins source/swagger/swagger_open_banking_fase4_apis.yml -o source/includes/partials_open_banking/_open_banking_fase4_apis.md.erb --user_templates source/templates/openapi3/ --language_tabs "javascript:JavaScript:request" "python:Python:request" "java:Java::request" --omitHeader --summary --httpsnippet

      # - uses: actions/cache@v1
      #   with:
      #     path: build
      #     key: ${{ runner.os }}-${{ hashFiles('**/source') }}

      # - run: bundle config set deployment 'true'
      # - run: bundle install
      # - run: bundle exec middleman build

      # Run Spectral
      # - uses: stoplightio/spectral-action@v0.7.0
      #   with:
      #     file_glob: "documentation/source/swagger/*_apis.yaml"

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./documentation/build
      
