name: Deploys
on:
  workflow_dispatch:
    inputs:
      build_id:
        description: 'ID of build to deploy'     
        required: true
jobs:
  deploy:
    name: Deploy Github pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: documentation
    env:
      ruby-version: 2.5
    steps:
      - run: echo 'Hello!'
