name: Deploy
on:
  workflow_dispatch:
    inputs:
      build_id:
        description: 'ID of build to deploy'     
        required: true
      integration_branch:
        description: 'Integration branch that contain build files to deploy.'
        required: true
jobs:
  deploy:
    name: Deploy Github pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: documentation
    env:
      ruby-version: 2.5
    steps:
      - uses: actions/checkout@v2
      - uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.AREADEV_INTEGRATION}}
          workflow: build.yml
          branch: ${{ github.event.inputs.integration_branch }}
          run_id: ${{ github.event.inputs.build_id }}
          name: build_folder_artifact
          path: ./documentation
      - run: tar -zxvf build.tar.gz
      - run: cp -Rf source/versions build/build
      - run: |
          ls -la
          ls -la build/build
 
      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./documentation/build/build
      
